### ISSUE TITLE
Colonists go wandering

### ISSUE THREAD

**Issue by Bartnaa** [rselbo/DermalRegenerator#3]
While this mod is active colonists go into a "wandering state and not doing any jobs. The following error comes up when a healthy save is loaded.

Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.MissingMethodException: System.Collections.Generic.List`1<Verse.Building> Verse.ListerBuildings.AllBuildingsColonistOfDef(Verse.ThingDef)
  at (wrapper dynamic-method) RimWorld.JobGiver_Work.RimWorld.JobGiver_Work.PawnCanUseWorkGiver_Patch2(RimWorld.JobGiver_Work,Verse.Pawn,RimWorld.WorkGiver)
  at (wrapper dynamic-method) RimWorld.JobGiver_Work.RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1(RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x000fb] in <cd7169108ea74757aa50c5b33d275c15>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch2 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()

**Comment by rselbo** [comment]
Nice, this is helpful.

**Comment by rselbo** [comment]
Unfortunately this is showing patched functions in the callstack so there are interactions with other mods. So I need to figure out what other mods it is interacting with but I can start by trying to implement a more complete version of the Job classes.

**Comment by rselbo** [comment]
The issue seems to be that some mod has patched some function and try to call a function that I probably should have implemented, Unfortunately I don't know what function yet.

**Comment by Bartnaa** [comment]
I tried it with just the DF mod alone with a new game and this is the new log for the same thing.

Message logging is now once again on.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Verse.Log:ResetMessageCount ()
Verse.Log:Clear ()
Verse.EditWindow_Log:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.MissingMethodException: System.Collections.Generic.List`1<Verse.Building> Verse.ListerBuildings.AllBuildingsColonistOfDef(Verse.ThingDef)
  at RimWorld.JobGiver_Work.PawnCanUseWorkGiver (Verse.Pawn pawn, RimWorld.WorkGiver giver) [0x00056] in <cd7169108ea74757aa50c5b33d275c15>:0 
  at RimWorld.JobGiver_Work.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x001de] in <cd7169108ea74757aa50c5b33d275c15>:0 
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x000fb] in <cd7169108ea74757aa50c5b33d275c15>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

**Comment by Bartnaa** [comment]
Save file on the following link [https://file.io/GbXIKIi7ADWa](url)

**Comment by rselbo** [comment]
Sorry i think i messed up so I didn't download the file and then it dissapeared. Would you mind uploading it again.

**Comment by Bartnaa** [comment]
New link
https://file.io/vpnscHNTyB81

**Comment by rselbo** [comment]
Uploaded a version that seems to work, closing this for now.
